// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZmAiJXPnNskFqXaKEtuVMKPANgmWNaXk',
    appId: '1:104681567962:android:73b3368b3fa88ba63897e3',
    messagingSenderId: '104681567962',
    projectId: 'flutter-apps-73734',
    databaseURL: 'https://flutter-apps-73734-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-apps-73734.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcnVr1y1dHrE2KCSbxptfMwdfERMAPvmM',
    appId: '1:104681567962:ios:76ebf046a5951d6b3897e3',
    messagingSenderId: '104681567962',
    projectId: 'flutter-apps-73734',
    databaseURL: 'https://flutter-apps-73734-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-apps-73734.firebasestorage.app',
    iosBundleId: 'com.example.flutterChat',
  );

}